project_identifier_env: try-docusaurus
api_key_env: 56daabeff353e52306067b1cf20c3b39
base_path: ./
preserve_hierarchy: true
files:
  - source: /docs/*.md
    translation: /website/translated_docs/%locale%/%original_file_name%
    languages_mapping:
      locale:
        th: th
  - source: /website/i18n/en.json
    translation: /website/i18n/%locale%.json
